export const icons = {
    dashboard: require("./dashboard.png"),
    profile: require("./profile.png"),
    routine: require("./training.png"),
    workout: require("./workout.png"),
    exercises: require("./exercises.png"),
    error: require("./error.png"),
    delete: require("./delete.png"),
    edit: require("./edit.png"),
    search: require("./search.png"),
    clear: require("./clear.png"),
    done: require("./done.png"),
    back: require("./back.png"),
    drag: require("./drag.png"),
    moveVert: require("./moveVert.png"),
    add: require("./add.png"),
}