export const icons = {
    dashboard: require("./dashboard.png"),
    profile: require("./profile.png"),
    routine: require("./training.png"),
    workout: require("./workout.png"),
    exercises: require("./exercises.png"),
    error: require("./error.png"),
    delete: require("./delete.png"),
    edit: require("./edit.png"),
    search: require("./search.png"),
    clear: require("./clear.png"),
    done: require("./done.png"),
    back: require("./back.png"),
    drag: require("./drag.png"),
    moveVert: require("./moveVert.png"),
    add: require("./add.png"),
    remove: require("./remove.png"),
    weight: require("./weight.png"),
    sets: require("./sets.png"),
    reps: require("./reps.png"),
    rest: require("./rest.png"),
    notes: require("./notes.png"),
    save: require("./save.png"),
    garbage: require("./garbage.png"),
    quick: require("./quick.png"),
    bolt: require("./bolt.png"),
}